#!/bin/bash
#
#================================ Set make environment variables ================================
#
# Related file storage path
current_path="${PWD}"
armbian_origin_img="${current_path}/armbian.img"
armbian_origin_dir="${current_path}/armbian"
armbian_rebuild_file="${current_path}/armbian-msm8916.img"
armbian_rebuild_dir="${current_path}/armbian-msm8916"
common_file="${current_path}/common-file/*"
kernel_deb="${current_path}/kernel/*.deb"
temp_img="${current_path}/temp.img"
temp_dir="${current_path}/temp"

choose_device() {
printf "请输入要构建的设备：1: UFI001C 2: UFI003\n"
read a
case "$a" in
1)
device="ufi001c"
;;
2)
device="ufi003"
;;
esac
}

make_img() {
    dd if=/dev/zero of=${temp_img} bs=1M count=1536
    dd if=/dev/zero of=${armbian_rebuild_file} bs=1M count=1234
    mkfs.btrfs ${armbian_rebuild_file}
    mkfs.btrfs ${temp_img}
}

mount_img() {
    mount -o compress=zstd:15 ${temp_img} ${temp_dir}
    mount -o compress=zstd:15 ${armbian_rebuild_file} ${armbian_rebuild_dir}
}

mount_etc() {
    mount --bind /proc ${temp_dir}/proc
    mount --bind /dev ${temp_dir}/dev
    mount --bind /dev/pts ${temp_dir}/dev/pts
    mount --bind /sys ${temp_dir}/sys
}

umount_etc() {
    umount ${temp_dir}/proc
    umount ${temp_dir}/dev/pts
    umount ${temp_dir}/dev
    umount ${temp_dir}/sys
}

umount_img() {
    umount ${temp_dir}
    umount ${armbian_rebuild_dir}
}

copy_file() {
    cp -rfp ${armbian_origin_dir}/* ${temp_dir}
    cp ${common_file} ${temp_dir}/tmp
    cp ${kernel_deb} ${temp_dir}/tmp
}

copy_modem_file() {
    cp ${current_path}/modem/firmware-${device}.deb ${temp_dir}/tmp
}

remove_file() {
    rm ${temp_dir}/tmp/*
}

mount_origin_armbian_img() {
    losetup -P /dev/loop404 ${armbian_origin_img}
    mount /dev/loop404p1 ${armbian_origin_dir}
}

umount_origin_armbian_img() {
    umount ${armbian_origin_dir}
    losetup -d /dev/loop404
}

resize_img() {
    cp -rfp ${temp_dir}/* ${armbian_rebuild_dir}
}

choose_device
mkdir ${armbian_origin_dir}
mkdir ${armbian_rebuild_dir}
mkdir ${temp_dir}
make_img
mount_img
mount_origin_armbian_img
copy_file
copy_modem_file
mount_etc
chroot ${temp_dir} /tmp/chroot.sh
remove_file
umount_etc
resize_img
umount_img
umount_origin_armbian_img
img2simg ${armbian_rebuild_file} rootfs.img
rm ${temp_img}
rm -rf ${armbian_origin_dir}
rm -rf ${armbian_rebuild_dir}
rm -rf ${temp_dir}